services:
  - type: web
    name: raj-portfolio-react
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
# npx serve -s dist